[package]
name = "algo-pro"
version = "0.1.0"
authors = ["Randi Apriansyah <papayura223@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
